# Bundles data/places.json + data/photos.json into data/site-data.js so the page
# works when opened straight off the filesystem (file://), where fetch() is blocked.
# Run this after editing either JSON file.
#
# Run:  powershell -ExecutionPolicy Bypass -File tools\build-data.ps1

$web = Split-Path -Parent $PSScriptRoot

$places = Get-Content (Join-Path $web "data\places.json") -Raw -Encoding UTF8
$photos = Get-Content (Join-Path $web "data\photos.json") -Raw -Encoding UTF8

# fail loudly rather than writing a broken bundle
try { $null = $places | ConvertFrom-Json } catch { throw "data/places.json is not valid JSON: $_" }
try { $null = $photos | ConvertFrom-Json } catch { throw "data/photos.json is not valid JSON: $_" }

$out = "/* GENERATED by tools/build-data.ps1 - do not edit. Edit data/places.json and data/photos.json. */`r`n" +
       "window.SITE_PLACES = $places;`r`n" +
       "window.SITE_PHOTOS = $photos;`r`n"

$path = Join-Path $web "data\site-data.js"
[IO.File]::WriteAllText($path, $out, (New-Object Text.UTF8Encoding $false))

Write-Output "wrote data/site-data.js ($((Get-Item $path).Length) bytes)"
