#!/usr/bin/env bash
# Bundles data/places.json + data/photos.json into data/site-data.js so the page
# works when opened straight off the filesystem (file://), where fetch() is blocked.
# Run this after editing either JSON file.
set -euo pipefail
cd "$(dirname "$0")/.."

{
  echo "/* GENERATED by tools/build-data.sh - do not edit. Edit data/places.json and data/photos.json. */"
  printf 'window.SITE_PLACES = '
  cat data/places.json
  printf ';\nwindow.SITE_PHOTOS = '
  cat data/photos.json
  printf ';\n'
} > data/site-data.js

echo "wrote data/site-data.js ($(wc -c < data/site-data.js) bytes)"
